### ISSUE TITLE
a_token已经获取到了，但是登录报错

### ISSUE THREAD

**Issue by iwwz** [pbbqdd/LTSignIn#1]
返回

b'{"loginCode":"homeNotLogged"}'
can't login

**Comment by pbbqdd** [comment]
token只要等号后面的值，你是不是吧“token=”也写在里面了 @iwwz

**Comment by iwwz** [comment]
就是等号后边一直到下一个c_id=之前的值，是这样吗@pbbqdd

**Comment by pbbqdd** [comment]
是的。

**Comment by iwwz** [comment]
直接获取了token值，可以运行了，感谢 @pbbqdd
