### ISSUE TITLE
~~已失效~~  询问一下是否失效

### ISSUE THREAD

**Issue by mixool** [pbbqdd/LTSignIn#2]
使用的是main下的test.py
通过packet_capture获取a_token后python3 test.py运行于VPS上
返回只有
can't login，没有更多信息了。
想知道是姿势不对，还是~~已失效~~

**Comment by pbbqdd** [comment]
尝试用一下dev分支的那个。那个活得时间长

**Comment by mixool** [comment]
感谢指导，之前抓包方法错了，用dev分支成功使用。
![session.png](https://i.loli.net/2019/04/28/5cc5525b92004.png)

**Comment by wfion** [comment]
> 感谢指导，之前抓包方法错了，用dev分支成功使用。
> ![session.png](https://camo.githubusercontent.com/170c92bb6fa12df634703d3205103384382a6bf5/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30342f32382f356363353532356239323030342e706e67)
> 
> 今天看到一个模板：https://qiandao.today/tpl/12202/edit
> 也许代码会对你写登陆有帮助，我刚接触python，还不会倒腾...
> 
> 又找到个轮子：https://github.com/hxer/simpleSignin/blob/master/signin/unicomapp.py#L12-L17
> python真好玩。

为啥你这个 能抓到登录请求 我就抓不到/MobileService/login的请求 只有访问首页的请求

**Comment by pbbqdd** [comment]
@wfion  看请求的具体内容。

**Comment by wfion** [comment]
@pbbqdd 
![screen](https://user-images.githubusercontent.com/9151381/63143588-a10dca00-c021-11e9-8812-061a0b0b902a.png)
只有这几个请求没看到登陆的  不过a_token我倒是能看到

**Comment by pbbqdd** [comment]
@wfion 需要用fidder 生成一个证书导入到手机里。这样才能解https的请求。

**Comment by wfion** [comment]
@pbbqdd 谢谢，我找到原因所在了 是我本地没有信任这个根证书的事情，我安卓模拟器是安装过证书的

**Comment by wfion** [comment]
@pbbqdd  你好 我根据自己的需求修改了你的项目，我把脚本发到我的github上，上面有您的链接和版权 您看可以吗？ 如果不行的话 我更新的代码发给你。我就把项目删除了

**Comment by mixool** [comment]
我写了个bash版本的，支持用户名密码登陆，不过怕滥用(违规刷金币)被封得太快没有开源，这里就放个只有签到功能的，真有需求其它功能的自己抓包添加吧，登陆后就一个curl请求的事:
```bash
#!/usr/bin/env bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

# user info: change them to yours or use parameters instead.
username="18500000000"
password="123456"

# UA and deviceId: if you failed to login , maybe you need to change it to your IMEI.
deviceId=$(shuf -i 123456789012345-987654321012345 -n 1)
UA="Mozilla/5.0 (Linux; Android 6.0.1; oneplus a5010 Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/52.0.2743.100 Mobile Safari/537.36; unicom{version:android@6.0100,desmobile:$username};devicetype{deviceBrand:Oneplus,deviceModel:oneplus a5010}"

# workdir
workdir="/root/daySign_LT_$username/"
[[ ! -d "$workdir" ]] && mkdir $workdir

function rsaencrypt() {
  cat > $workdir/rsa_public.key <<-EOF
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDc+CZK9bBA9IU+gZUOc6
FUGu7yO9WpTNB0PzmgFBh96Mg1WrovD1oqZ+eIF4LjvxKXGOdI79JRdve9
NPhQo07+uqGQgE4imwNnRx7PFtCRryiIEcUoavuNtuRVoBAm6qdB0Srctg
aqGfLgKvZHOnwTjyNqjBUxzMeQlEC2czEMSwIDAQAB
-----END PUBLIC KEY-----
EOF

  crypt_username=$(echo -n $username | openssl rsautl -encrypt -inkey $workdir/rsa_public.key -pubin -out >(base64 | tr "\n" " " | sed s/[[:space:]]//g))
  crypt_password=$(echo -n $password | openssl rsautl -encrypt -inkey $workdir/rsa_public.key -pubin -out >(base64 | tr "\n" " " | sed s/[[:space:]]//g))
}

function urlencode() {
  local length="${#1}"
  for (( i = 0; i < length; i++ )); do
    local c="${1:i:1}"
    case $c in
		[a-zA-Z0-9.~_-]) printf "$c" ;;
		*) printf "$c" | xxd -p -c1 | while read x;do printf "%%%s" "$x";done
    esac
  done
}

function login() {
    rsaencrypt
    cat > $workdir/signdata <<-EOF
isRemberPwd=true
&deviceId=$deviceId
&password=$(urlencode $crypt_password)
&netWay=Wifi
&mobile=$(urlencode $crypt_username)
&yw_code: 
&timestamp=$(date +"%Y-%m-%d_%H-%M-%S" | awk -F'[-_-]' '{print $1$2$3$4$5$6}')
&appId=dda726c5e6aa1ee96e62a88ecae46f11ca76450dccf0c249db7648480bd25b11a9c31ac1b63373a2d19e500dc5ae5351edcbf1917674d55fcc9e9f171ebb66b0
&keyVersion=1
&deviceBrand=Oneplus
&pip=10.0.$(shuf -i 1-255 -n 1).$(shuf -i 1-255 -n 1)
&provinceChanel=general
&version=android%406.0100
&deviceModel=oneplus%20a5010
&deviceOS=android6.0.1
&deviceCode=$deviceId
EOF

  # cookie
  curl -s -H "$UA" -D $workdir/cookie "https://m.client.10010.com/mobileService/logout.htm" >/dev/null
  curl -s -H "$UA" -b $workdir/cookie -c $workdir/cookie -d @$workdir/signdata "http://m.client.10010.com/mobileService/login.htm" >/dev/null
  token=$(cat $workdir/cookie | grep -E "a_token" | awk  '{print $7}')
  [[ "$token" = "" ]] && echo "Error, login failed." && echo "cmd for clean: rm -rf $workdir" && exit 1
}

function daySign() { 
  echo; echo $(date) starting daySign...
  curl -s -H "$UA" -b $workdir/cookie -c $workdir/cookie_da --data "token=$token" "https://act.10010.com/SigninApp/signin/querySigninActivity.htm" >/dev/null

  # goldTotal_before
  echo goldTotal_before：$(curl -s -H "$UA" -b $workdir/cookie_da "https://act.10010.com/SigninApp/signin/goldTotal.do")

  # daySign_status
  echo daySign_status： $(curl -s -H "$UA" -b $workdir/cookie_da "https://act.10010.com/SigninApp/signin/daySign.do")
  
  # weiboSign_status
  timestamp=$(date +"%Y-%m-%d_%H-%M-%S" | awk -F'[-_-]' '{print $1$2$3$4$5$6}')
  random_weibo_stamp=$(shuf -i 123456789012345-987654321012345 -n 1)
  echo weiboSign_status：$(curl -s -H "$UA" -b $workdir/cookie_da --data "transId=$timestamp$(shuf -i 0-9 -n 1).$random_weibo_stamp&userNumber=$username&taskCode=TA590934984&finishTime=$timestamp&taskType=DAILY_TASK" https://act.10010.com/signinAppH/commonTask)
  
  # goldlottery: 3 times free each day and 13 times total.
  usernumberofjsp=$(curl -s -H "$UA" -b $workdir/cookie_da http://m.client.10010.com/dailylottery/static/textdl/userLogin | grep -oE "encryptmobile=\w*" | awk -F"encryptmobile=" '{print $2}')
  for((i = 1; i <= 3; i++)); do
  [[ $i -gt 3 ]] && curl -s -H "$UA" -b $workdir/cookie_da --data "goldnumber=10&banrate=10&usernumberofjsp=$usernumberofjsp" http://m.client.10010.com/dailylottery/static/doubleball/duihuan >/dev/null; sleep 1
  echo lottery_$i: $(curl -s -H "$UA" -b $workdir/cookie_da --data "usernumberofjsp=$usernumberofjsp" http://m.client.10010.com/dailylottery/static/doubleball/choujiang); sleep 1
  done
  
  # goldTotal_now
  echo goldTotal_now：$(curl -s -H "$UA" -b $workdir/cookie_da "https://act.10010.com/SigninApp/signin/goldTotal.do")
}

function main() {
  #sleep $(shuf -i 1-10800 -n 1)
  login
  daySign
  
  # clean
  rm -rf $workdir

  # exit
  echo; echo $(date) $username Accomplished.  Thanks!
}

main
```

**Comment by wfion** [comment]
@mixool 为啥不用py写呢，我这昨天研究两个py才研究明白。bash我能看懂，不想研究了😭   语言间的不同客服太困难了。想弄个全局变量赋值都很费劲

**Comment by mixool** [comment]
@wfion 因为我py只勉强能看看代码，bash熟悉一点。

**Comment by wfion** [comment]
@mixool  流量封顶不是虚假的吗，我用超40g也没断网啊？ 像你说的不也就是一个请求的事。。。

**Comment by mixool** [comment]
@wfion 一天分享消息刷了几千金币，把树苗搞到最高等级后，觉得金币没啥用了。也就给卡开个封顶看上去有点用...

**Comment by pbbqdd** [comment]
@wfion 可以随便用。

**Comment by pbbqdd** [comment]
> 我写了个bash版本的，支持用户名密码登陆，不过怕滥用被封得太快没有开源，这里就放个只有签到功能的，真有需求其它功能的自己抓包添加吧，登陆获得cookie后就一个curl请求的事:
> 
> ```shell
> #!/usr/bin/env bash
> PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
> export PATH
> 
> # user info: change them to yours.
> username="18500000000"
> password="123456"
> 
> # UA and deviceId: if you failed to login , maybe you need to change it to your IMEI.
> deviceId=$(shuf -i 123456789012345-987654321012345 -n 1)
> UA="Mozilla/5.0 (Linux; Android 6.0.1; oneplus a5010 Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/52.0.2743.100 Mobile Safari/537.36; unicom{version:android@6.0100,desmobile:$username};devicetype{deviceBrand:Oneplus,deviceModel:oneplus a5010}"
> 
> # workdir
> workdir="/root/daySign_LT_$username/"
> [[ ! -d "$workdir" ]] && mkdir $workdir
> 
> function rsaencrypt() {
>   cat > $workdir/rsa_public.key <<-EOF
> -----BEGIN PUBLIC KEY-----
> MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDc+CZK9bBA9IU+gZUOc6
> FUGu7yO9WpTNB0PzmgFBh96Mg1WrovD1oqZ+eIF4LjvxKXGOdI79JRdve9
> NPhQo07+uqGQgE4imwNnRx7PFtCRryiIEcUoavuNtuRVoBAm6qdB0Srctg
> aqGfLgKvZHOnwTjyNqjBUxzMeQlEC2czEMSwIDAQAB
> -----END PUBLIC KEY-----
> EOF
> 
>   crypt_username=$(echo -n $username | openssl rsautl -encrypt -inkey $workdir/rsa_public.key -pubin -out >(base64 | tr "\n" " " | sed s/[[:space:]]//g))
>   crypt_password=$(echo -n $password | openssl rsautl -encrypt -inkey $workdir/rsa_public.key -pubin -out >(base64 | tr "\n" " " | sed s/[[:space:]]//g))
> }
> 
> function urlencode() {
>   local length="${#1}"
>   for (( i = 0; i < length; i++ )); do
>     local c="${1:i:1}"
>     case $c in
> 		[a-zA-Z0-9.~_-]) printf "$c" ;;
> 		*) printf "$c" | xxd -p -c1 | while read x;do printf "%%%s" "$x";done
>     esac
>   done
> }
> 
> function login() {
>     rsaencrypt
>     cat > $workdir/signdata <<-EOF
> isRemberPwd=true
> &deviceId=$deviceId
> &password=$(urlencode $crypt_password)
> &netWay=Wifi
> &mobile=$(urlencode $crypt_username)
> &yw_code: 
> &timestamp=$(date +"%Y-%m-%d_%H-%M-%S" | awk -F'[-_-]' '{print $1$2$3$4$5$6}')
> &appId=dda726c5e6aa1ee96e62a88ecae46f11ca76450dccf0c249db7648480bd25b11a9c31ac1b63373a2d19e500dc5ae5351edcbf1917674d55fcc9e9f171ebb66b0
> &keyVersion=1
> &deviceBrand=Oneplus
> &pip=10.0.$(shuf -i 1-255 -n 1).$(shuf -i 1-255 -n 1)
> &provinceChanel=general
> &version=android%406.0100
> &deviceModel=oneplus%20a5010
> &deviceOS=android6.0.1
> &deviceCode=$deviceId
> EOF
> 
>   # cookie
>   curl -s -H "$UA" -D $workdir/cookie "https://m.client.10010.com/mobileService/logout.htm" >/dev/null
>   curl -s -H "$UA" -b $workdir/cookie -c $workdir/cookie -d @$workdir/signdata "http://m.client.10010.com/mobileService/login.htm" >/dev/null
>   token=$(cat $workdir/cookie | grep -E "a_token" | awk  '{print $7}')
>   [[ "$token" = "" ]] && echo "Error, login failed." && echo "cmd for clean: rm -rf $workdir" && exit 1
> }
> 
> function daySign() { 
>   echo; echo $(date) starting daySign...
>   curl -s -H "$UA" -b $workdir/cookie -c $workdir/cookie_da --data "token=$token" "https://act.10010.com/SigninApp/signin/querySigninActivity.htm" >/dev/null
> 
>   # goldTotal_before
>   echo goldTotal_before：$(curl -s -H "$UA" -b $workdir/cookie_da "https://act.10010.com/SigninApp/signin/goldTotal.do")
> 
>   # daySign_status
>   echo daySign_status： $(curl -s -H "$UA" -b $workdir/cookie_da "https://act.10010.com/SigninApp/signin/daySign.do")
>   
>   # weiboSign_status
>   timestamp=$(date +"%Y-%m-%d_%H-%M-%S" | awk -F'[-_-]' '{print $1$2$3$4$5$6}')
>   random_weibo_stamp=$(shuf -i 123456789012345-987654321012345 -n 1)
>   echo weiboSign_status：$(curl -s -H "$UA" -b $workdir/cookie_da --data "transId=$timestamp$(shuf -i 0-9 -n 1).$random_weibo_stamp&userNumber=$username&taskCode=TA590934984&finishTime=$timestamp&taskType=DAILY_TASK" https://act.10010.com/signinAppH/commonTask)
>   
>   # goldlottery: 3 times free each day and 13 times total.
>   usernumberofjsp=$(curl -s -H "$UA" -b $workdir/cookie_da http://m.client.10010.com/dailylottery/static/textdl/userLogin | grep -oE "encryptmobile=\w*" | awk -F"encryptmobile=" '{print $2}')
>   for((i = 1; i <= 3; i++)); do
>   [[ $i -gt 3 ]] && curl -s -H "$UA" -b $workdir/cookie_da --data "goldnumber=10&banrate=10&usernumberofjsp=$usernumberofjsp" http://m.client.10010.com/dailylottery/static/doubleball/duihuan >/dev/null; sleep 1
>   echo lottery_$i: $(curl -s -H "$UA" -b $workdir/cookie_da --data "usernumberofjsp=$usernumberofjsp" http://m.client.10010.com/dailylottery/static/doubleball/choujiang); sleep 1
>   done
>   
>   # goldTotal_now
>   echo goldTotal_now：$(curl -s -H "$UA" -b $workdir/cookie_da "https://act.10010.com/SigninApp/signin/goldTotal.do")
> }
> 
> function main() {
>   #sleep $(shuf -i 1-10800 -n 1)
>   login
>   daySign
>   
>   # clean
>   rm -rf $workdir
> 
>   # exit
>   echo; echo $(date) $username Accomplished.  Thanks!
> }
> 
> main
> ```

bash写程序太复杂了。我这种半吊子搞不了。

**Comment by wfion** [comment]
@mixool 分享消息这么多金币吗？我看了好像都次数限制啊
我对现在新出的那个等级感兴趣。

**Comment by mixool** [comment]
分享一次加二金币，无上限。
等级那些任务都能用代码完成...

**Comment by wfion** [comment]
@mixool  求私发地址，现在网页上好像这个分享一次给2金币的都没了

**Comment by mixool** [comment]
@wfion 联通快报点分享按钮 app判断成功分享后会给你加2金币，这个不在金币任务里面。自己抓包请求，然后伪造就行了。
