### ISSUE TITLE
emmm

### ISSUE THREAD

**Issue by tata9898** [pbbqdd/LTSignIn#3]
铁 我推荐你在客户端用 触动精灵那一类的脚本把  从UI入手  也简单

**Comment by tata9898** [comment]
那个a_tooken 我好想简单过 前几天我把他cookies都拼起来了 然后没时间 我特么就放弃了 日。。。 我再去看看

**Comment by tata9898** [comment]
那个a_token 在之前 https://m.client.10010.com/mobileService/onLine.htm 这样的一样网址 
<img width="827" alt="image" src="https://user-images.githubusercontent.com/25726968/66711940-dc313d00-edc7-11e9-8f5c-07b52e3e58e4.png">

**Comment by pbbqdd** [comment]
@tata9898  这个脚本就是早期实现。为了跑在家里服务器上自用的。如有需要可以尝试dev分支的脚本，master分支已经不用了。

**Comment by tata9898** [comment]
emmm  我已经实现了 拿crontab跑上了

**Comment by tata9898** [comment]
> @tata9898 这个脚本就是早期实现。为了跑在家里服务器上自用的。如有需要可以尝试dev分支的脚本，master分支已经不用了。

抽奖 和分享那个 求私发一波 。。。。蟹蟹大佬。
